version: '3'
services:
    php:
        build: .
        volumes:
            - ./src:/var/www/html
        container_name: php-server
        restart: always
        ports:
            - 8080:80
        networks:
            - marvel
    nginx:
        image: nginx:1.13.0-alpine
        volumes:
            - ./docker/marvelAlvaro.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/html
        links:
            - php
        ports:
            - "80:80"
        networks:
            - marvel

networks:
    marvel:
        external:
            name: marvel_network
